name: Generate Binaries

on:
  push:
    branches: ['main']
    paths: ['config.t0rch.json']

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUPPORTED_PLATFORMS: |
        ( 
          "darwin-amd64" 
          "windows-386" 
          "linux-arm" 
        )

    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.1
      
      - name: Install go-selfupdate
        run: go install github.com/sanbornm/go-selfupdate/cmd/go-selfupdate@latest

      - uses: actions/checkout@v3
      - name: Generate Binaries
        run: |
          next_version=$(cat config.t0rch.json | jq '.version')
          echo ${next_version}
          mkdir ./tmp
          platforms=${{ env.SUPPORTED_PLATFORMS }}
          for p in ${platforms[*]}
          do
            touch ./tmp/$p
          done
          ~/go/bin/go-selfupdate ./tmp ${next_version}
      
      - name: Commit Generated Binaries
        run: |
          git config --global user.name 'muezz'
          git config --global user.email 'muezz7055@gmail.com'
          git commit -am "t0rch version bump: ${next_version}"
          git push
