name: Test

on:
  push:
    branches: ['dev']
    paths: ['config.t0rch.json']

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUPABASE_PROJECT_ID: conqcdxbczhqszglmwyk
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
      SUPPORTED_PLATFORMS: |
        ( 
          "darwin-amd64" 
          "windows-386" 
          "linux-arm" 
        )

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: Previous Version
        id: previous-version
        run: |
          previous_version=$(git show HEAD~1:config.t0rch.json | jq -r '.version')
          echo ${previous_version}
          echo "previous_version=$previous_version" >> $GITHUB_OUTPUT

      - name: Get current version
        id: current-version
        run: |
          current_version=$(cat config.t0rch.json | jq '.version')
          echo ${current_version}
          echo "current_version={current_version}" >> $GITHUB_OUTPUT
      
      - name: Compare Versions
        uses: jackbilestech/semver-compare@1.0.4
        with:
          head: ${{ steps.current-version.outputs.current_version }}
          base: ${{ steps.previous-version.outputs.previous_version }}
          operator: ">"
      
