name: Upload New Version to Supabase Bucket

on:
  push:
    branches:
      - main

jobs:
  upload-to-supabase:
    runs-on: ubuntu-latest

    env:
      SUPABASE_PROJECT_ID: conqcdxbczhqszglmwyk
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Get current version
        id: current-version
        run: |
          current_version=$(ls public | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "::set-output name=version::$current_version"

      - name: Get previous version
        id: previous-version
        run: |
          git fetch origin main --depth=1
          previous_version=$(git show origin/main:public | grep -E '^[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)
          echo "::set-output name=version::$previous_version"

      - name: Check if new version exists
        id: check-new-version
        run: |
          if [ "${{ steps.current-version.outputs.version }}" != "${{ steps.previous-version.outputs.version }}" ]; then
            echo "New version detected: ${{ steps.current-version.outputs.version }}"
            echo "::set-output name=new_version::true"
          else
            echo "No new version detected"
            echo "::set-output name=new_version::false"
          fi
      
      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: 1.169.8
      
      - name: Init Supabase Project
        run: supabase init
      
      - name: Link Supabase Project
        run: supabase link --project-ref ${{ env.SUPABASE_PROJECT_ID }}
      
      - name: Upload to Supabase
        if: steps.check-new-version.outputs.new_version == 'true'
        run: |
          supabase storage cp -r ./public/${{ steps.current-version.outputs.version }} ss:///t0rch/${{ steps.current-version.outputs.version }}/ --experimental
